### PR TITLE
Truncate table cell text

### LINKED ISSUE #913: Add documentation for Table.Column
We should add docs and a Props Table for the `Table.Column` to be able to show the props and usage of the Column. This one, we can showcase the sorting properties and many more.

### PR DESCRIPTION
**Pull request by francocorreasosa**
Fixes https://github.com/auth0/cosmos/issues/857
Fixes #913 

image
~Need to merge #914 and rebase #915 from master to make tests pass here.~ Done

### CODE REVIEW

**Comment by francocorreasosa** [comment]
Can you take a look? @landitus & @siddharthkp (I added the table to all `<table>` in the docs)

**Comment by francocorreasosa** [comment]
Oops!  Forgot to update the `stressed with truncating` story. Now it's fixed, sorry. Please note that by default, truncating is not being applied, so the normal stressed story won't have it applied anyway.

**Comment by landitus** [comment]
Would `truncate` be a better prop name than `truncating`?

**Comment by francocorreasosa** [comment]
For me it's the same, I can change it if you want. We could use `truncated` as well.

**Comment by landitus** [comment]
Let's go with `truncate` as it's shorter and more common.

**Comment by francocorreasosa** [comment]
Done 😄

**Comment by landitus** [comment]
I've noticed that when setting a truncated column combined with a percentage width, the table breaks.  It looks like it's not simple to make this work in tables. My guess is that it's easier to set percentages for widths, and also having two properties that break is not a good idea. 

From these answers, seems there are a bunch of options:
- https://stackoverflow.com/questions/5239758/css-truncate-table-cells-but-fit-as-much-as-possible

Seems many rely on hacks... which is not a good sign.

**Comment by siddharthkp** [comment]
@francocorreasosa This has a bunch of unrelated chromatic changes 😢 

Can you replicate this PR from a fresh master? 🙏

**Comment by francocorreasosa** [comment]
Yeah it’s weird. I think there are unapproved changes on master as well. Will review when I get to the office

**Comment by francocorreasosa** [comment]
@siddharthkp I think in this kind of cases is better to _request changes_ than applying the `don't merge` label. Just for the sake of not mixing the purposes (I've seen `don't merge` is mostly used on WIP and _opened for staging` PRs.

**Pull request closed without merging**
