### PR TITLE
Replaced colliding Booleans with enums in Button and Tooltip

### LINKED ISSUE #364: Change use of Booleans to enums wherever they could collide
After some debate (see #88) we've decided to avoid the use of multiple Boolean props to control a single aspect of components, and instead use an enumeration. This will result in slightly more ugly code, but avoids potential issues where different properties could collide.

### PR DESCRIPTION
**Pull request by nkohari**
Closes #364.
Related to #88.

This patch combines the `default`, `primary`, `transparent`, `link`, and `destructive` props on `Button` into a single enumeration called `intent`. The name of this prop is debatable; there were several suggestions, so I just picked one that was more descriptive than `type`. 😄 

The `disabled`, `loading`, and `success` props are left as Booleans, and they influence (or override) the styles set by intents. It's still technically possible for these state-oriented properties to collide, but it's reasonable to have a combination of two. For example, you might want to disable a button while a form is saving, so you might set it both `disabled` and `loading`.

In `Tooltip`, the `top` and `bottom` props are combined into a `position` enum. We could just eliminate the `top` prop and keep the `bottom` prop as a Boolean. However, if we decided to add more positions in the future, it would either end up as a breaking change or result in an inconsistent API.

### CODE REVIEW

**Comment by landitus** [comment]
Nice!!

I think we are going to have more positions for the tooltip, so it's nice to have the position enum!

**Comment by landitus** [comment]
@nkohari Just a heads up, there are some docs and components in the overview that still have the old button syntax, like https://auth0-cosmos-enums.now.sh/docs/ButtonGroup

**Comment by siddharthkp** [comment]
Looks really good!

Should the _state_ of the button be grouped together as well? 

Right now, one conflicting half is grouped, but the other conflicting half isn't.

`<Button intent="transparent" disabled loading success>Button</Button>`


Suggested: 
```jsx
<Button intent="transparent" state="disabled">Button</Button>
<Button intent="transparent" state="loading">Button</Button>
<Button intent="transparent" state="success">Button</Button>

```

**Comment by siddharthkp** [comment]
>  but it's reasonable to have a combination of two. For example, you might want to disable a button while a form is saving, so you might set it both disabled and loading.

Combinations would definitely exist, but I don't consider that to be part of the API or job of the user 

Example: `<Button intent="primary" state="loading">Button</Button>` would be a blue button with the loading circle and disabled for clicks.

Related: https://github.com/auth0/cosmos/issues/87

**Comment by nkohari** [comment]
Whoops! Sorry about that, I'll fix it momentarily.

**Comment by nkohari** [comment]
While I was fixing the remaining problems, I realized that Form Actions have a property called `appearance` which we're just passing along to the `Button` as `intent`. Maybe `appearance` is the right name. 😄

**Comment by siddharthkp** [comment]
I'd say pick one you like and we'll rename it later/whenever

**Comment by beneliflo** [comment]
vote `appearance` 👍

**Comment by landitus** [comment]
I like appearance too

**Comment by nkohari** [comment]
Appearance it is!

**Pull request merged**
