### PR TITLE
Fix "Hello World" message

### PR DESCRIPTION
**Pull request by radlinskii**
Changed the "Hello World" message to be less 1337.

### CODE REVIEW

**Comment by francocorreasosa** [comment]
Hey! Can you rebase your PR from our current `master`? So we can get it run from the CI and merge it. Thanks

**Comment by radlinskii** [comment]
Sure, I will try to do that

**Comment by radlinskii** [comment]
I hope it works now

**Comment by francocorreasosa** [comment]
@radlinskii Just merged the fix to our master. One more rebase and we'd be ok 👌

**Comment by radlinskii** [comment]
Ok I will do it in a few hours

**Comment by francocorreasosa** [comment]
Awesome, thank you very much!

**Comment by radlinskii** [comment]
Finally! 😄

**Pull request merged**
