### PR TITLE
Add ResourceList and ResourceListItem components

### PR DESCRIPTION
**Pull request by nkohari**
This patch implements the beginning of the `ResourceList` component discussed in #394.

The documentation still needs to be improved, and I haven't replaced the existing implementation in Client List, but I wanted to share it to get feedback.

### CODE REVIEW

**Comment by landitus** [comment]
Looks good! I just caught a visual regression with the List. It’s about the action buttons position and the width of columns. Could we add the test to chromatic before moving forward? So we test it against the current design on 0.0.1

**Comment by nkohari** [comment]
Yep, that's a good idea! Like we were saying, good for us to get in the habit of making sure we have coverage before merging. 😀

**Comment by landitus** [comment]
So far I've seen one visual bug, which might be related to https://github.com/auth0/cosmos/issues/517

The tooltip for the button group is not centered to the button. It looks like it's using the spacing of the margin as well.

**Comment by nkohari** [comment]
Hmm... you're right. It isn't a regression in this patch though; here's the behavior with the old `ClientList` on `master`:

screen shot 2018-04-24 at 8 37 53 am

I'll create a new issue to fix this in another patch, but it shouldn't stop us from merging this.

**Comment by landitus** [comment]
Sounds good.

Sent from Astro <https://www.helloastro.com> for Mac

On 24 Apr 2018 at 09:39, Nate Kohari <notifications@github.com> wrote:


Hmm... you're right. It isn't a regression in this patch though; here's the
behavior with the old ClientList on master:

[image: screen shot 2018-04-24 at 8 37 53 am]
<https://user-images.githubusercontent.com/1576/39187274-d989c268-479a-11e8-9b62-099770b35554.png>

I'll create a new issue to fix this in another patch, but it shouldn't stop
us from merging this.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/auth0/cosmos/pull/504#issuecomment-383915001>, or mute
the thread

**Pull request merged**
