### PR TITLE
Fix avatar props in docs issue.

### LINKED ISSUE #611: Props table breaks on Avatar docs page
The default props on the `Avatar` docs page don't appear correctly in the table, and when you input props manually, it overrides the defaults with blank props.

Here's a gif of the issue:

I'm not sure if this issue occurs elsewhere in the docs. @landitus discovered it when reviewing the new `Avatar` PR, and we realized it's already an issue on master.

### PR DESCRIPTION
**Pull request by francocorreasosa**
Resolves #611

### CODE REVIEW

**Comment by landitus** [comment]
Just spotted some chromatic regressions @francocorreasosa!

**Comment by landitus** [comment]
Yep, they are definitely from avatar-block, the original branch!

**Comment by francocorreasosa** [comment]
This PR goes to `avatar-block`, not `master` @landitus

**Comment by landitus** [comment]
Cool, then we'll deal with these in avatar-block. Thanks @francocorreasosa !

**Comment by landitus** [comment]
@nkohari This one has conflicts

**Comment by nkohari** [comment]
Closed in favor of #637. (The original `avatar-block` branch was rebased and squashed, so cherry picking was easier than resolving the merge on this branch.)

**Pull request closed without merging**
