### PR TITLE
Support target in link for EmptyState and AvatarBlock

### PR DESCRIPTION
**Pull request by siddharthkp**
Fixes https://github.com/auth0/cosmos/issues/683

Supports both string and shape

```js
PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.shape({
    href: PropTypes.string,
    target: PropTypes.string
  })
])
```

Concerns:

1. If we are accepting an object, will folks expect other props will be passed on as well? like `onClick` for link. Should we do that and pass the object forward as props? `<Link {...props.helpUrl} />`

2. The result in `AvatarBlock` is slightly weird because the prop itself called `href` but supports `href = {{ href: 'auth0.com', target: '_blank' }}`

    We probably need to standardise the prop name and call it `link` or something

### CODE REVIEW

**Comment by nkohari** [comment]
Is this marked don't merge because it's still in progress, or are you just looking for reviews?

**Comment by landitus** [comment]
The standard way then would be:
```
link = {{ href: 'auth0.com', target: '_blank' }}
```?

Which components would be affected to create a consistent API?

**Comment by siddharthkp** [comment]
@nkohari 

> Is this marked don't merge because it's still in progress, or are you just looking for reviews?

Sorry missed this

Not happy with the API, so definitely a work in progress. 

Also, looking for feedback to land on a good API


> I think that forwarding the entire object on to Link as props makes sense. I also agree that we should deprecate href on EmptyState and rename the prop to link for clarity.
> link = {{ href: 'auth0.com', target: '_blank' }}

Looks good to me!

**Comment by siddharthkp** [comment]
Looking good now: 

```jsx
<EmptyState
  icon="clients"
  title="Clients"
  link={{ href: 'https://auth0.com', target: '_blank' }}
/>
```

The object format also supports extra parameters which are ...proxied to the `Link` element 🎉 

Final question, do we want to support both string and object for `link`, Or should we lock down on object?

screen shot 2018-08-31 at 2 27 15 pm

**Comment by landitus** [comment]
> Final question, do we want to support both string and object for link, Or should we lock down on object?

What's your take @siddharthkp ?

**Comment by siddharthkp** [comment]
I'd say let's support both

**Pull request merged**
