### PR TITLE
Alerts: Add support for icons

### PR DESCRIPTION
**Pull request by siddharthkp**
Fixes https://github.com/auth0/cosmos/issues/899

```jsx
 <Alert icon="help" type="default" title="FYI!">Long form message goes here</Alert>
```

Preview: [staging](https://auth0-cosmos-alerts-with-icon.now.sh/docs/#/component/alert)

Side note: The snyk tests failed because we moved the location of tests, can safely ignore that (I guess)

### CODE REVIEW

**Comment by landitus** [comment]
This is a good start! We'll have to do a few things:
- Make the color of the icon the same as the text (depends on the type of alert)
- Add visual tests for alert + icons (showcase all alert types)
screen shot 2018-09-17 at 10 59 37

**Comment by landitus** [comment]
mm, we may need to do a tweak with positioning. Let's try these icons first:
[buddicons.zip](https://github.com/auth0/cosmos/files/2388993/buddicons.zip)

**Comment by siddharthkp** [comment]
The note icon looks weird in the app 😅

image

**Comment by landitus** [comment]
Will re-export it, then

**Pull request merged**
