### PR TITLE
Input color change in the tokens

### PR DESCRIPTION
**Pull request by landitus**
Closes: https://github.com/auth0/cosmos/issues/765

### CODE REVIEW

**Comment by landitus** [comment]
This change of the border color in the inputs is not triggering any chromatic changes. Can you check @siddharthkp ?

**Comment by siddharthkp** [comment]
Doens't look it's a bug in our code base!

Reproduced in https://github.com/auth0/cosmos/pull/812 and reported to chromatic folks

It seems like the color change is too subtle to be caught by visual tests /shrug

**Comment by siddharthkp** [comment]
We can totally merge this PR though

**Comment by landitus** [comment]
Ok, let’s

**Comment by siddharthkp** [comment]
Got a reply. Yep it's a little too tiny for the diffing to catch

```
Hey Sid, I took a closer look at this and it seems like a false negative due to the anti-aliasing detection in our diff algorithm. I am going to be reworking this anyway in the next few weeks and I'll aim to solve this as part of that.

Cheers,
Tom
```

**Comment by landitus** [comment]
Thanks for the update, and it’s good they are trying to solve it! No small change should pass, jajaja.

**Pull request merged**
