### PR TITLE
More prominent version switcher for docs

### PR DESCRIPTION
**Pull request by landitus**
Improved the switcher to be more prominent :)

screen shot 2018-09-28 at 19 47 13

### CODE REVIEW

**Comment by francocorreasosa** [comment]
In Safari (macOS Mojave) looks like this:
image

In Firefox (Dev Edition):
image

Is this expected?

**Comment by landitus** [comment]
Yep, we are using the native select, so I expect it to look different cross-browser. I believe that to achieve a unified look, we have to style the select with a custom select (hide the native, recreate the select behaviour). So it's something we can improve when we get to the custom select.

**Comment by francocorreasosa** [comment]
Just noticed this also happens in our Select component. Maybe we can reset that with `-webkit-appearance: none;`? What do you think?

**Comment by francocorreasosa** [comment]
Looks goooooood! 🙌

**Comment by landitus** [comment]
Thanks!!

**Pull request merged**
