### PR TITLE
New tokens>color

### PR DESCRIPTION
**Pull request by beneliflo**
updated master with tokens>colors

### CODE REVIEW

**Comment by siddharthkp** [comment]
This is a scary PR 😅

I'm going to pick it up after https://github.com/auth0/cosmos/issues/162, so that it's easier to review 😄

**Comment by siddharthkp** [comment]
There seem to be more changes which are unrelated. 

If these are intentional, great! If not, reverse them 

1. Some colors are different

This affects button colors, text color, input border

colors

2. Alignment and weight of form label has changed.

alignment

**Comment by siddharthkp** [comment]
For icons, should we add another section in `tokens/colors` or use one of the pre-existing ones?

`Icon` uses a default color [`colors.base`](https://github.com/auth0/cosmos/blob/master/src/components/atoms/icon.js#L44)

`EmptyState` is a new component which [adds `colors.grayMedium` to icon](https://github.com/auth0/cosmos/blob/master/src/components/atoms/empty-state.js#L23)

**Comment by beneliflo** [comment]
https://github.com/auth0/cosmos/pull/163#issuecomment-356217769

1. Are different because only use are a few colors of grays. Many other varieties are being used in the sketch. The input-border, helper, error text and others don't match the color that is in the sketch.

2. Weight as I said befor. Alignment has changed for some weight but is more easy to fix 😄

**Comment by siddharthkp** [comment]
Backmerging master here, hold on :)

**Comment by siddharthkp** [comment]
🎉

**Pull request merged**
