### PR TITLE
Makes the dialog responsive, accessible and flexible

### PR DESCRIPTION
**Pull request by andresgalante**
@francocorreasosa This is a work in progress PR of the dialog box.

So far it includes a more robust CSS implementation that makes it flexible and responsive, and changes on the HTML structure to make it accessible. 

**Still to do:**

- [x] Fix dialog HTML and CSS
- [x] Make the dialog accecible following standards
- [x] Make the dialog responsive
- [x] Define focus behavior
- [x] implement focus behavior (@francocorreasosa) 
- [x] Define dialog sizes (@landitus)
- [x] implement  dialog sizes (@francocorreasosa)
- [x] Improve action button with an icon so it's not blue
- [x] Define a strategy to include tabs on a dialog.
- [x] Understand a clean the overlay component
- [x] Create stories for each use cases
- [x] Document the component
- [x] Move the maxwidth prop to overlay instead of the dialog box
- [x] Fix tabs HTML and CSS
- [x] docs, why is a dialog `category: Layout` @landitus ?
- [x] Make sure it works crossborowser
- [x] Make the type of heading optional  (@francocorreasosa)
- [x] Change the overlay position to match Manage
- [x] Improve CSS for tabs on dialogs
- [x] Change the overlay background to match Manage
- [ ] Add examples on code snippets on the dialog docs

**Other thoughts that are out of scope from this issue:**

- Make tabs accessible
  - https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel
- Make all components semtaically correct by fixing their HTML structure
- Review and fix CSS in all components
- Write guidelines for:
  - How to write HTML and CSS
  - Create a margin strategy for components and implement it
  - Improve the token system
  - Accessibility
  - and others base system definitions
- Is `ButtonGroup` a tool bar?
- Touch areas are too small
- Visuals are not accessible: font size and color contrast
- Define with the team a strategy to document how to handle forms on dialog
- Create a template for documentation
- DEfine how to handle focus rings system-wide

### CODE REVIEW

**Comment by siddharthkp** [comment]
@landitus @francocorreasosa Should we polish this up to merge in it's current state?

**Comment by landitus** [comment]
This is looking awesome. I have a few things to review (I denied them in chromatic). But I can't check this branch out locally or see a deploy.

These are my comments:
- I believe there is a new button appearance introduced in this PR. Mostly to be able to do a coloured icon. Note this change affects the examples that use it, mainly the Resource List. So I believe we need to update those examples as well. I want to check this out before merging. 
- The Dialog should have center-aligned Tabs. Shall we do this is a different PR?

**Comment by siddharthkp** [comment]
Hi!

This PR is super old and does a bunch of things:

- New button appearance
- Touches Tabs
- Button group bug fix?

That's scary, should we break this down into multiple PRs on top of current master?

**Comment by siddharthkp** [comment]
This was implemented by https://github.com/auth0/cosmos/pull/1102

**Pull request closed without merging**
