### PR TITLE
[WIP] Change `Client Type` anchors to radio on dialog

### PR DESCRIPTION
**Pull request by beneliflo**
Tracking https://github.com/auth0/cosmos/issues/376

The principal idea what we talk with @landitus is change `anchors` to `radio` option in the selection of the `Client Type`. This is more effective in the use and the right semantic to this kind of options.
Maybe the engineering isn't my strong but is good to have to @siddharthkp 😄

This is an approach. Now this escalates and we have to build a component for this. 😅 

WDYT?

### CODE REVIEW

**Comment by landitus** [comment]
Just want to add that these radio button disguised like cards are a potencial global component. We have them in use prominently in the onboarding. I'll post screenshots

**Comment by siddharthkp** [comment]
Overall looks real good to me. 

With one minor code change:

I know this isn't your code (hi @nkohari!), but `Client.Element` or `Client.RadioElement` is a style that we use inside cosmos so that we can export it and override it.

I'd not want others to learn this pattern in the example app, it should be easy-peasy.

Because it's in the same file, I'd just replace that with 

```js
const RadioElement = styled.a``
```

and use that.

**Comment by nkohari** [comment]
This has [WIP] in the title, so I'm assuming it shouldn't be merged? I added the `don't merge` label for the meantime.

**Comment by nkohari** [comment]
@landitus @beneliflo Anyone know why this is still marked don't merge? Is this ready to go or should we abandon it? (See also #376.)

**Comment by nkohari** [comment]
Closed since this has become stale. Will rework later using `Radio`.

**Pull request closed without merging**
