### PR TITLE
Fix bug in Avatar block with link option

### PR DESCRIPTION
**Pull request by beneliflo**
Fixes: #788 

fixed line-height when avatarBlock has a link

### CODE REVIEW

**Comment by nkohari** [comment]
@landitus Can you review this so we can get it merged?

**Comment by beneliflo** [comment]
@landitus I added some examples in the docs.

**Comment by landitus** [comment]
@beneliflo can you add a test for the Avatar block with the link activated, in all available sizes?

**Comment by francocorreasosa** [comment]
Closing in favor of #810

**Pull request closed without merging**
