### PR TITLE
 Added prepend and append content to Text Input via @m4tr1k

### LINKED ISSUE #1082: Add support for prepend and append content to Text Input
We need the ability to enhance the **text input** with units, icons and text. 

**Examples:**
_____ .auth0.com
_____ seconds
Icon _____
$ ________ (this example doesn't exist but it wouldn't hurt to add it)
 
screen shot 2018-11-13 at 13 01 53

image

### PR DESCRIPTION
**Pull request by francocorreasosa**
Continues #1089 
Resolves #1082

### CODE REVIEW

**Comment by francocorreasosa** [comment]
Hey @m4tr1k. The tests are failing and I'm getting this as soon as I try to open the docs:
image

**Comment by m4tr1k** [comment]
Hi @francocorreasosa! I would like to take a look at it, I will try to do that today, if not I will do it tomorrow, because I need to study...
Thank you

**Comment by m4tr1k** [comment]
@francocorreasosa I did some things to fix the problem, and I want to commit here, but I don't know how to do it. On my local fork I have pushed the commit, but I can't push it here

**Comment by francocorreasosa** [comment]
If things are running as expected and tests are passing (run `yarn scripts test.unit.watch`) on your local branch send another PR and I can bring the code to this branch.

**Comment by siddharthkp** [comment]
Hey! This is a great implementation. 

But, it doesn't quite match what we have in mind (We don't expect you to read our minds of course)

I'll have to close this PR 😢 

When we write up the design spec for the TextInput, that would be a good time to tackle this component again. (the offer is open, you don't have to of course)

**Comment by m4tr1k** [comment]
Hi @siddharthkp. It's ok, I will certainly do that when you write up the design spec for the TextInput.
My first idea was to do that on another component, but I thought you wanted that on the same component

**Pull request closed without merging**
