### PR TITLE
Table columns can now be passed as external children

### PR DESCRIPTION
**Pull request by sanketsingh24**
Now you can store all the columns in a variable and pass that children as a variable, albeit as first-child only. Fixes- #893 

```jsx
const defaultItems = [
  {
    name: 'Harry Kane',
    goals: 6,
    assists: 0,
    country: '🇬🇧',
    image: 'https://twitter-avatar.now.sh/HKane'
  },
  {
    name: 'Romelu Lukaku',
    goals: 4,
    assists: 1,
    country: '🇧🇪',
    image: 'https://twitter-avatar.now.sh/Romelu_lukaku9'
  },
  {
    name: 'Antoine Griezmann',
    goals: 4,
    assists: 2,
    country: '🇫🇷',
    image: 'https://twitter-avatar.now.sh/AntoGriezmann'
  },
  {
    name: 'Ivan Perišić',
    goals: 3,
    assists: 1,
    country: '🇭🇷',
    image: 'https://twitter-avatar.now.sh/ivanperisic44'
  }
]

const columns = (<div>
      <Table.Column field="image" width="50px">
        {item => <Avatar type="user" image={item.image} />}
      </Table.Column>
      <Table.Column field="name" title="Name" width="30%" />
      <Table.Column field="country" title="Country" />
      <Table.Column field="goals" title="Goals" />
      <Table.Column field="assists" title="Assists" />
</div>)


const Example = () => {
  return <Table items={defaultItems}>{columns}</Table>
}

render(Example)
```

### CODE REVIEW

**Comment by sanketsingh24** [comment]
@francocorreasosa can you please review this if its ok?

**Comment by francocorreasosa** [comment]
Hey! Can you rebase your PR from our current `master`? So we can get it run from the CI and merge it. Thanks

**Comment by sanketsingh24** [comment]
Ok, will do that soon.

**Comment by francocorreasosa** [comment]
Hey @sanketsingh24, I moved this to #1035 so we can run tests and merge it. Thanks!

**Pull request merged**
