### PR TITLE
Made secondary button's border darker

### LINKED ISSUE #823: Secondary button's border doesn't play well with some gray backgrounds
We would need to make the border darker to avoid that

### PR DESCRIPTION
**Pull request by Axle7XStriker**
Since secondary button's border was too light and therefore did not play well with some grey backgrounds, as suggested I have made the border darker.

fixes #823

### CODE REVIEW

**Comment by Axle7XStriker** [comment]
Didn't get why the travis-build failed can anyone explain it to me please.

**Comment by francocorreasosa** [comment]
@Axle7XStriker can you rebase from current master please?

**Comment by siddharthkp** [comment]
@Axle7XStriker 👋 

> Didn't get why the travis-build failed can anyone explain it to me please.

Explanation here: https://github.com/auth0/cosmos/issues/989

**Comment by Axle7XStriker** [comment]
Done. Please see to it.

**Comment by francocorreasosa** [comment]
@Axle7XStriker Just merged the fix to our master. One more rebase and we'd be ok 👌

**Comment by siddharthkp** [comment]
@Axle7XStriker Sorry! I'll do it

**Comment by siddharthkp** [comment]
Merging this into a local branch `button-secondary-border` so that CI can run. More info here: https://github.com/auth0/cosmos/issues/989

Here's the staging url: https://auth0-cosmos-button-secondary-border.now.sh/docs

Merged the PR ✨ Would be deployed with the next release

**Pull request merged**
