### PR TITLE
Tokens v2 example (feedback needed)

### PR DESCRIPTION
**Pull request by siddharthkp**
1. Read the proposal and comments here: https://github.com/auth0/cosmos/issues/479

2. Already found colors that were in tokens and not used, the new structure prevents that

3. Chromatic tests passed = no breaking changes

4. This is still a work in progress, the code is nowhere close to what it should be like

### CODE REVIEW

**Comment by landitus** [comment]
I'm going to use a bunch of these tokens inside within this branch to test the new setup. Once we have a good idea if they work, we'll merge to master.

**Comment by siddharthkp** [comment]
@landitus How was your experience using these?

**Comment by siddharthkp** [comment]
How can I make this pull request easier to review 😄

**Comment by nkohari** [comment]
If this is in a usable state, I think we should just merge it. This is the second PR for the second level of tokens, and I'd hate to abandon it again. :)

**Comment by siddharthkp** [comment]
This PR is only good for example, it doesn't implement enough tokens/components

We can close this

**Comment by landitus** [comment]
Sorry for the delay. Like it a lot! Let's move this forward!

**Pull request closed without merging**
