### PR TITLE
Pull docs to internal

### PR DESCRIPTION
**Pull request by siddharthkp**
work in progress

depends on https://github.com/auth0/cosmos/pull/575 for `/redirect`

### CODE REVIEW

**Comment by nkohari** [comment]
Is this ready to go now that #575 has been merged?

**Comment by siddharthkp** [comment]
@nkohari We're good now!

**Comment by landitus** [comment]
Would it make sense to have the docs in `/docs` instead of `internal/docs` ?

**Comment by siddharthkp** [comment]
File structure: There's more to come in internal like overview, sandbox, etc.

URL: It's still accessible at the same url of auth0-cosmos.now.sh/docs


Here's the plan:

map

**Comment by landitus** [comment]
perfect!

**Pull request merged**
