### PR TITLE
Add {props} to emptyState example

### LINKED ISSUE #488: Empty State propTable won't update on helpUrl prop
screen shot 2018-04-09 at 20 51 33

Checking the Empty State propTable, I've noticed it won't when addind the helpUrl prop. It seems like an issue with the propsTable component.

### PR DESCRIPTION
**Pull request by siddharthkp**
Fixes #488

The docs are more interactive now, but not copy-friendly because of the repeated props (see staging)

This is a bigger problem, we don't have a way of adding defaults props for just the docs, details: https://github.com/auth0/cosmos/issues/259

I'm not sure if this change is n+1 or n-1, what do you think?

### CODE REVIEW

**Comment by landitus** [comment]
I don't see the repeating props. Looks fine to me!

screen shot 2018-04-10 at 21 09 33


We can also discuss #259. Sorry I totally missed it!

**Comment by siddharthkp** [comment]
> I don't see the repeating props

Try adding icon or title

**Comment by nkohari** [comment]
Yeah, I think your instincts were right on this @siddharthkp ... I'm not sure this is a good change unless we can find a way to eliminate the redundant properties. It definitely looks like a bug in the docs, and I think it will be confusing if someone copies and pastes it. (We'll definitely get bug reports about it. :D)

**Comment by nkohari** [comment]
I think we have consensus that this shouldn't be merged as-is, and it's a larger issue that might need some refactoring of `Playground`. Unless anyone has a problem with it, I'm going to close this PR and we can circle back to it another time.

**Comment by siddharthkp** [comment]
@nkohari Don't know if it's too late, but https://github.com/auth0/cosmos/pull/496 should make this PR possible?

**Comment by siddharthkp** [comment]
Now, this PR is n + 1

**Pull request merged**
