### PR TITLE
Fix Form.Radio example does not working on docs

### PR DESCRIPTION
**Pull request by jvelezpo**
Form.Radio example does not work on docs

Fixes: https://github.com/auth0/cosmos/issues/839

[x] tests passes

### CODE REVIEW

**Comment by francocorreasosa** [comment]
Hey! Can you rebase your PR from our current `master`? So we can get it run from the CI and merge it. Thanks

**Comment by jvelezpo** [comment]
> Hey! Can you rebase your PR from our current `master`? So we can get it run from the CI and merge it. Thanks

I will do it tonight 👍

**Comment by francocorreasosa** [comment]
@jvelezpo Just merged the fix to our master. One more rebase and we'd be ok 👌

**Comment by francocorreasosa** [comment]
Moved to #1032 to check CI and Staging. Thanks!

**Pull request merged**
