### PR TITLE
Apply line-height only to sc- components

### PR DESCRIPTION
**Pull request by siddharthkp**
The only difference between the resets of the styleguide and cosmos is `line-height`

We want cosmos components to have our line-height, but not break everything else, hence as a hack, we're setting it on styled-components elements.
 
Note: This will break on applications that already use styled-components

### CODE REVIEW

**Comment by siddharthkp** [comment]
@landitus Need a review of the components to make sure nothing unintentional happened. chromatic thinks so.

**Comment by landitus** [comment]
Let me check it out

**Comment by landitus** [comment]
I need to fix some numbers to make the buttons look ok with the new line height and also fix a design bug I caught today. I need to make sure the buttons and inputs align properly when displayed in the same line

**Comment by landitus** [comment]
Got the changes but I think they exceed the scope of this PR. @siddharthkp lmk if you still want me to push the changes to this branch.

**Comment by siddharthkp** [comment]
@landitus Updated the tests, now there are 6 files

**Comment by landitus** [comment]
I have some conflicts when merging these changes, so I'll need help @siddharthkp

**Comment by landitus** [comment]
I've solved the conflicts, so it's up for review!

**Pull request merged**
