### PR TITLE
Made checkbox, radio and switch accessible with a keyboard

### LINKED ISSUE #871: Checkbox has no visible :focus style
A `:focus` style is essential for keyboard users trying to use a `Checkbox` component.

### PR DESCRIPTION
**Pull request by DCzajkowski**
I went ahead and made checkbox, radio and switch accessible with a keyboard. It adds a pretty outline to the controls when they are focused. Used the color similar to the one proposed by @francocorreasosa. Fixes #871.

### CODE REVIEW

**Comment by francocorreasosa** [comment]
Hi @DCzajkowski! Thank you for your contribution! I'm trying to fix the build since we have an issue with a CI hook on forked repositories. Will get back to you when fixed.

**Comment by DCzajkowski** [comment]
Sure thing 💪

**Comment by francocorreasosa** [comment]
@DCzajkowski Just merged the fix to our master. One more rebase and we'd be ok 👌

**Comment by francocorreasosa** [comment]
@DCzajkowski Can you rebase this from our current `master`? So we can run the tests and merge it. Thanks!

**Comment by DCzajkowski** [comment]
Done. 😉

**Comment by francocorreasosa** [comment]
Thanks

**Pull request merged**
