### PR TITLE
Fixes the duplicate options in the docs. (#1540)

### PR DESCRIPTION
**Pull request by francocorreasosa**
via @ubenzer 

screen shot 2019-03-07 at 3 52 26 pm

### CODE REVIEW

**Comment by francocorreasosa** [comment]
Removing `{props}` from markdown causes the prop table to be unable to pass props to the component 😞  

Example: https://auth0-cosmos-1540-doc-fix.now.sh/docs/#/component/select

**Comment by ubenzer** [comment]
Oh, I see what you mean. Maybe we can close this PR and I can report this as a bug. Wdyt?

**Comment by francocorreasosa** [comment]
Sure, let's do that

**Comment by ubenzer** [comment]
https://github.com/auth0/cosmos/issues/1542

**Comment by francocorreasosa** [comment]
@ubenzer Thanks a lot 🙇

**Pull request closed without merging**
