### PR TITLE
Fix page header

### PR DESCRIPTION
**Pull request by beneliflo**
Tracking issues https://github.com/auth0/cosmos/issues/315

### CODE REVIEW

**Comment by nkohari** [comment]
This needs to be squashed and rebased against the current master. There are a lot of small commits here that will confuse the history, and after the other patch (#321) was landed there are a lot of conflicts. 😄

**Comment by landitus** [comment]
Where you able to do the rebase @beneliflo ? Let us know if you need help

**Comment by beneliflo** [comment]
conflicts solved

**Comment by landitus** [comment]
I've done just a few tweaks!

Pushed some a more fleshed out documentation page :)

@siddharthkp Can you show us how to document these props for the Page Header docs?

```
actions={{
		primaryAction: {
			label: 'Create Client',
			icon: 'plus',
			method: null
		},
		secondaryAction: {
			label: 'Tutorial',
			icon: 'play-circle',
			method: null
		}
	}}
```

**Comment by siddharthkp** [comment]
You can them by using `shape` ([link to docs](https://reactjs.org/docs/typechecking-with-proptypes.html))

We do this in `Form.Actions`, [here's the code](https://github.com/auth0/cosmos/blob/master/src/components/molecules/form/actions/index.js#L58-L67)

I'm not sure if the docs do a good job of displaying 2 level nesting, we'll find out 😉

**Comment by beneliflo** [comment]
conflicts solved

**Pull request merged**
