### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by francocorreasosa**
Fix tests for changes introduced prior to merging component tests to master.

### CODE REVIEW

**Comment by siddharthkp** [comment]
The tests in parallel made it really difficult to parse the logs, so I've changed it to series

**Comment by siddharthkp** [comment]
Doesn't look like the chromatic tests are getting triggered from us. Checking the logs

(Sorry, I should have caught it on the previous PR, I assumed chromatic was down)

**Comment by landitus** [comment]
Can you check and merge @siddharthkp ?

**Comment by siddharthkp** [comment]
It's pretty opaque what's happening here

screen shot 2018-09-12 at 5 45 36 pm

**Comment by landitus** [comment]
🤭

**Pull request merged**
