### PR TITLE
Tooltip in button group UI fixes + Tooltip stories

### LINKED ISSUE #764: Unit tests for tooltip
Testing tooltips is tricky

Because it's only visible in hover, our visual tests don't catch it!

### PR DESCRIPTION
**Pull request by francocorreasosa**
Fixes #764

### CODE REVIEW

**Comment by francocorreasosa** [comment]
@landitus I think this is ready to merge after you review it 👍

**Comment by landitus** [comment]
Looks good to me! I would only add one more test, which is when the button with icon invokes the tooltip. Like: https://auth0-cosmos.now.sh/docs/#/component/button#adding-tooltips

This is a quick shortcut that only covers the top alignment, but we can test it too.

**Comment by francocorreasosa** [comment]
Sure thing!

**Comment by francocorreasosa** [comment]
Done. @landitus

**Pull request merged**
