### PR TITLE
Docs: Fix production version + implement caching

### PR DESCRIPTION
**Pull request by siddharthkp**
Fixes https://github.com/auth0/cosmos/issues/873

### CODE REVIEW

**Comment by siddharthkp** [comment]
Chromatic tests seem stuck :cry

**Comment by landitus** [comment]
Version number looking good!

**Comment by landitus** [comment]
@siddharthkp what should we do next to put this on production?

**Comment by siddharthkp** [comment]
> @siddharthkp what should we do next to put this on production?

Chromatic pipelines were down during the day, it's back now

**Comment by landitus** [comment]
Ok!

**Comment by landitus** [comment]
I't's still showing the incorrect number 😅

**Comment by siddharthkp** [comment]
Gotta wait for deployment 😛

**Pull request merged**
