### PR TITLE
[DXDP-88] Composable actions for Tabs in Dialog 

### LINKED ISSUE #1217: No margin at the bottom of Dialog in Firefox
**Describe the bug**
No bottom padding at the bottom of a scrollable alert in Firefox

**Expected behavior**
To look the same as in Chrome

**Screenshots**

In Firefox
image

In Chrome
image

**Cosmos version:**
v0.9.x

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by francocorreasosa**
Resolves #1217 
Related to #951 

As we all know, we're having problems with the Dialog + Tabs combination since with the current implementation, we can't vary footer items for each tabs in the Dialog.

In order to solve this, I propose adding the option to provide a `Dialog.Footer` element as direct children to `Tabs.Tab` .

Example:
```diff
 <Dialog title={'This is a test with composable actions'} open={true}>
        <Tabs selected={this.state.selected} onSelect={this.handleChange}>
          <Tabs.Tab label="Test 1st tab">
            <p>Are you sure</p>

+           <Dialog.Footer key="1st-tab-footer">
+             <Button appearance="secondary">Cancel</Button>
+             <Button appearance="cta">Send</Button>
+           </Dialog.Footer>
          </Tabs.Tab>
          <Tabs.Tab label="Test 2nd tab">
            <p>This is a test Tab panel</p>


+           <Dialog.Footer key="2nd-tab-footer">
+             <Button appearance="cta">Enable add-on</Button>
+           </Dialog.Footer>
          </Tabs.Tab>
        </Tabs>
      </Dialog>
```

In the case you're providing each tab's content as an independent view, this is pretty useful since you don't need to know the whole Tabs element state to vary each tab footer actions.

This implementation does not require any extra CSS at the application level.

Here's a working example: https://auth0-cosmos-franco-exp-composable-actions.now.sh/sandbox/?selectedKind=Dialog&selectedStory=composed%20dialog%20with%20tabs&full=0&addons=1&stories=1&panelRight=0

Please, let me know what you think, the current implementation is experimental and I will add testing to this feature only if we agree on keeping it.

### CODE REVIEW

**Comment by cristiandouce** [comment]
By quick inspecting the code it'd seem imposible to think of using the `Dialog.Footer` component if there are no tabs in it.

I know that the intention is to solve that current issue, but it'd seem that it'd only apply for this specific use case and it'd be impossible to abstract any others.

Would it be too crazy to abstract the usage to support both the current API and something similar to:

```jsx
<Dialog title="" ...>
  <Dialog.Body> my content here</Dialog.Body>
  <Dialog.Footer>my footer here</Dialog.Footer>
</Dialog>
```

So, for the tabs problem, it'd look something like

```jsx
<Dialog title="" ...>
  <Tabs ...>
    <Tabs.Tab id="1">
      <Dialog.Body>My content for tab 1 - no footer</Dialog.Body>
    </Tabs.Tab>
    <Tabs.Tab id="2">
      <Dialog.Body>My content for tab 2 - with footer!</Dialog.Body>
      <Dialog.Footer>my footer here</Dialog.Footer>
    </Tabs.Tab>
  </Tabs>
</Dialog>
```

**Comment by francocorreasosa** [comment]
@cristiandouce Yeah that’s totally possible to do. I didn’t do it before since I thought we didn’t want that.

**Comment by francocorreasosa** [comment]
@cristiandouce Okay so this is now working:

- **Compose header and footer for each tab**: https://auth0-cosmos-franco-exp-composable-actions.now.sh/sandbox/?selectedKind=Dialog&selectedStory=composed%20dialog%20with%20tabs&full=0&addons=1&stories=1&panelRight=0
- **Compose dialog without tabs**: https://auth0-cosmos-franco-exp-composable-actions.now.sh/sandbox/?selectedKind=Dialog&selectedStory=composed%20dialog&full=0&addons=1&stories=1&panelRight=0

**Comment by francocorreasosa** [comment]
@andresgalante I'll need a review on https://github.com/auth0/cosmos/pull/1458/commits/69044ce6059e7a7f810b6b96f66386063624bba7 when you have a chance.

**Comment by siddharthkp** [comment]
Honestly, I don't like this too much 😢 


Things I like - breaking Dialog into composable elements: Dialog.Body and Dialog.Footer

Things I don't like:

1. The cross cutting logic of Tabs in dialog.js feels wrong.

2. In [the first example](https://auth0-cosmos-franco-exp-composable-actions.now.sh/sandbox/?selectedKind=Dialog&selectedStory=composed%20dialog%20with%20tabs&full=0&addons=1&stories=1&panelRight=0
), changing Tabs also changes the title **outside** the Tab breaks hierarchy and hence would be very difficult to guess. 


&nbsp;

Would it be possible to create an API that looks like this. 

Notice how you can't change the title via the API. (However it's still possible to do it with user managed state, of course - which is the right place to handle it)

```jsx
<Dialog title="Example Dialog">
    <Tabs>
      <Tabs.Tab label="Tab 1">
        <Dialog.Body>Are you sure you want to delete My Computer</Dialog.Body>
        <Dialog.Actions>
          <Button>Yes, delete it</Button>
          <Button>nuuuuu, Cancel</Button>
        </Dialog.Actions>
      </Tabs.Tab>
      <Tabs.Tab label="Tab 2">
        <Dialog.Body>This tab only has information, no actions<Dialog.Body>
		<Dialog.Actions>
          <Button>Got it, thanks</Button>
        </Dialog.Actions>
      <Tabs.Tab>
    </Tabs>
</Dialog>
```

**Comment by francocorreasosa** [comment]
@siddharthkp I know what you mean, to me this is not the ideal solution either. I'm going to look further for a CSS way to resolve this, but I couldn't come up with a good one till now.

**Comment by landitus** [comment]
Sounds good to me!

**Pull request merged**
