### PR TITLE
Add conflict handling for prop table

### PR DESCRIPTION
**Pull request by siddharthkp**
🎉

switches

### CODE REVIEW

**Comment by landitus** [comment]
Awesome!

**Comment by landitus** [comment]
I can't see the deployment, but locally it looks good. Just catched a bug thanks to this. :) When the buttons are disabled, most combined states stay the same. For example:

screen shot 2018-02-14 at 18 12 42

The disabled destructive button should be visually dimmed.

**Comment by landitus** [comment]
But this LGTM!

**Comment by siddharthkp** [comment]
Fixed in https://github.com/auth0/cosmos/pull/280

**Pull request merged**
