### PR TITLE
[WIP] Adding support for TypeScript declarations

### PR DESCRIPTION
**Pull request by jcenturion**
The goal of this PR is to add support for Visual Studio Code IntelliSense by adding [TypeScript declarations](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html).

## TSD for components

- [x] Tooltip
- [x] Thumbnail
- [x] TextArea
- [x] TextInput
- [x] Switch
- [x] Spinner
- [x] Select
- [x] Radio
- [x] Button
- [x] Alert
- [x] Avatar
- [x] Code
- [x] Heading
- [x] Icon
- [x] Image
- [x] Label
- [x] Link
- [x] Logo
- [x] Overlay
- [x] Paragraph
- [ ] Button group
- [ ] Dialog
- [ ] Empty state
- [ ] Form group
- [ ] Form
- [ ] List
- [ ] Page header
- [ ] Resource list
- [ ] Sidebar
- [ ] Stack
- [ ] Table
- [ ] Tabs

## Demo

tsd-cosmos

### CODE REVIEW

**Comment by siddharthkp** [comment]
Love the feature!

@jcenturion @nkohari Can this be automated using metadata? 😅

**Comment by jcenturion** [comment]
@siddharthkp I'm making a little script for autogenerate the TypeScript declarations from PropTypes.

**Comment by siddharthkp** [comment]
Perfect!

You might want to use the metadata.json file that we generate

**Comment by luisrudge** [comment]
This is amazing! But my experience is that this type of stuff will get undoubtedly out-of-date. Wouldn't it be better if we built the library itself in typescript? This way you get always-up-to-date typings for free.

**Comment by siddharthkp** [comment]
> But my experience is that this type of stuff will get undoubtedly out-of-date

My hope is that if we automate it and put it as a part of our release process, it won't get outdated.

> Wouldn't it be better if we built the library itself in typescript? This way you get always-up-to-date typings for free.

Definitely, not sure if that's a priority for us though (comes at a cost of learning curve in the team + tooling)

**Comment by jcenturion** [comment]
@siddharthkp I've created a separate PR which adds autogeneration of TSD files => https://github.com/auth0/cosmos/pull/628.

**Pull request closed without merging**
